import { copyFileSync, existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { nowIso, type ForgeProgress, type ForgeTask } from "../state/progress.js";

/**
 * Forward-slash relative path to the handoff file. Hooks and skills key off
 * this exact string, so it must not vary across platforms.
 */
const HANDOFF_RELATIVE = ".forge/handoff.md";

/**
 * Returns the relative path of handoff.md from the project root, using
 * forward slashes for cross-platform consistency.
 */
export function handoffRelativePath(): string {
  return HANDOFF_RELATIVE;
}

/**
 * Returns the absolute path of handoff.md inside cwd.
 */
export function handoffAbsolutePath(cwd: string): string {
  return join(cwd, ".forge", "handoff.md");
}

const PLACEHOLDER = "—";

type HandoffFields = {
  feature: string;
  status: ForgeProgress["status"] | "idle";
  tasksRatio: string;
  deferredCount: number;
  lastTask: { id: number; title: string; commit: string | null } | null;
  nextTask: { id: number; title: string; scenarios: string[] } | null;
  specPath: string;
  planPath: string;
  generatedAt: string;
};

/**
 * Compute the structured fields rendered into handoff.md from a progress
 * snapshot. Pure: no I/O, no time read other than the explicit `now` arg.
 */
function extractFields(progress: ForgeProgress, now: string): HandoffFields {
  const deferredCount = progress.tasks.filter((t) => t.status === "deferred").length;

  // Last task: highest-id task with status "done". If none, null.
  const doneTasks = progress.tasks
    .filter((t) => t.status === "done")
    .sort((a, b) => a.id - b.id);
  const lastDone = doneTasks.length > 0 ? doneTasks[doneTasks.length - 1] : null;

  // Next task: lowest-id task with status "pending". Tasks in
  // progress are treated as the next thing to resume on.
  const pendingTasks = progress.tasks
    .filter((t) => t.status === "pending" || t.status === "in_progress")
    .sort((a, b) => a.id - b.id);
  const nextPending = pendingTasks.length > 0 ? pendingTasks[0] : null;

  return {
    feature: progress.feature ?? PLACEHOLDER,
    status: progress.status,
    tasksRatio: `${progress.completed_tasks}/${progress.total_tasks}`,
    deferredCount,
    lastTask: lastDone
      ? {
          id: lastDone.id,
          title: lastDone.title,
          commit: lastDone.commit ?? null,
        }
      : null,
    nextTask: nextPending
      ? {
          id: nextPending.id,
          title: nextPending.title,
          scenarios: scenarioTagsOf(nextPending),
        }
      : null,
    specPath: progress.spec_path ?? PLACEHOLDER,
    planPath: progress.plan_path ?? PLACEHOLDER,
    generatedAt: now,
  };
}

/**
 * Pull scenario tags off a task. Convention: tags starting with `S` followed
 * by digits (e.g. `S007`). Other tags (free-form) are ignored for handoff.
 */
function scenarioTagsOf(task: ForgeTask): string[] {
  if (!task.tags) return [];
  return task.tags.filter((tag) => /^S\d+$/.test(tag));
}

/**
 * Render handoff.md content from a progress snapshot. Pure string output —
 * no I/O. The shape (column-aligned key:value lines) is the canonical seed
 * format read by /resume, PreCompact hooks, and SessionStart hooks; do NOT
 * reorder or rename fields without updating those consumers.
 */
export function renderHandoff(progress: ForgeProgress, now?: string): string {
  const fields = extractFields(progress, now ?? nowIso());

  const lines: string[] = [];
  lines.push("# Forge Handoff");
  lines.push(
    `<!-- auto-generated by forge at ${fields.generatedAt} -->`,
  );
  lines.push("");
  lines.push(`Feature:    ${fields.feature}`);
  lines.push(`Status:     ${fields.status}`);
  lines.push(
    `Tasks:      ${fields.tasksRatio} done (deferred: ${fields.deferredCount})`,
  );

  if (fields.lastTask) {
    lines.push(
      `Last task:  ${fields.lastTask.id} — ${fields.lastTask.title}`,
    );
    if (fields.lastTask.commit) {
      lines.push(
        `Last commit: ${fields.lastTask.commit} (forge task-${fields.lastTask.id})`,
      );
    } else {
      lines.push(`Last commit: ${PLACEHOLDER}`);
    }
  } else {
    lines.push(`Last task:  ${PLACEHOLDER}`);
    lines.push(`Last commit: ${PLACEHOLDER}`);
  }
  lines.push("");

  if (fields.nextTask) {
    const scenariosValue =
      fields.nextTask.scenarios.length > 0
        ? fields.nextTask.scenarios.join(", ")
        : PLACEHOLDER;
    lines.push("Next task:");
    lines.push(`  id:    ${fields.nextTask.id}`);
    lines.push(`  title: ${fields.nextTask.title}`);
    lines.push(`  scenarios: ${scenariosValue}`);
    lines.push(`  spec:  ${fields.specPath}`);
    lines.push(`  plan:  ${fields.planPath}`);
  } else {
    lines.push(`Next task:  ${PLACEHOLDER}`);
    lines.push(`  spec:  ${fields.specPath}`);
    lines.push(`  plan:  ${fields.planPath}`);
  }

  lines.push("");
  lines.push(`generated_at: ${fields.generatedAt}`);
  lines.push("");
  lines.push("Resume command: /resume");
  lines.push("");

  return lines.join("\n");
}

/**
 * Atomically (re)write `.forge/handoff.md` with the rendered content. Always
 * a full overwrite — never appended — so that a stale handoff cannot leak
 * old field values into compaction seeds.
 */
export function writeHandoff(cwd: string, progress: ForgeProgress): void {
  const target = handoffAbsolutePath(cwd);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, renderHandoff(progress), "utf8");
}

/**
 * Forward-slash relative path to the archived handoff for a finished feature.
 * Mirrors the scenarios:archive layout (`.forge/specs/<feature>-scenarios.json`)
 * so a finished feature's complete record lives in one directory.
 */
export function handoffArchiveRelativePath(feature: string): string {
  return `.forge/specs/${feature}-handoff.md`;
}

/**
 * Move handoff.md to `.forge/specs/<feature>-handoff.md` and remove the live
 * file. Returns the archive path (relative, forward slashes) on success, or
 * null when there was nothing to archive (live handoff.md missing).
 *
 * Used by phase:finish so the executing-phase seed is preserved as part of
 * the feature's permanent record while clearing the live signal that hooks
 * use to drive compaction recovery.
 */
export function archiveHandoff(
  cwd: string,
  feature: string,
): string | null {
  const live = handoffAbsolutePath(cwd);
  if (!existsSync(live)) return null;

  const archiveRel = handoffArchiveRelativePath(feature);
  const archiveAbs = join(cwd, archiveRel);
  mkdirSync(dirname(archiveAbs), { recursive: true });
  copyFileSync(live, archiveAbs);
  rmSync(live, { force: true });
  return archiveRel;
}

/**
 * Loose, line-based view of a handoff.md file. Only the fields needed for
 * drift checks are extracted — anything else (commit, scenarios, paths) is
 * omitted because /audit's drift surface deliberately stays narrow.
 */
export type ParsedHandoff = {
  feature: string | null;
  status: string | null;
  /** "<done>/<total>" string as it appears in the Tasks: line */
  tasksRatio: string | null;
  deferredCount: number | null;
  /** id of the last_task as parsed from "Last task:  N — title", or null */
  lastTaskId: number | null;
  nextTaskId: number | null;
};

/**
 * Parse the structured fields out of a handoff.md body. Accepts the format
 * produced by renderHandoff(); tolerates trailing whitespace and missing
 * sections (returning nulls). NOT a full markdown parser.
 */
export function parseHandoff(content: string): ParsedHandoff {
  const out: ParsedHandoff = {
    feature: null,
    status: null,
    tasksRatio: null,
    deferredCount: null,
    lastTaskId: null,
    nextTaskId: null,
  };

  const featureMatch = content.match(/^Feature:\s*(.+)$/m);
  if (featureMatch) {
    const value = featureMatch[1].trim();
    out.feature = value === "—" ? null : value;
  }

  const statusMatch = content.match(/^Status:\s*(.+)$/m);
  if (statusMatch) {
    out.status = statusMatch[1].trim();
  }

  const tasksMatch = content.match(
    /^Tasks:\s*(\d+\/\d+)\s+done\s*\(deferred:\s*(\d+)\)/m,
  );
  if (tasksMatch) {
    out.tasksRatio = tasksMatch[1];
    out.deferredCount = parseInt(tasksMatch[2], 10);
  }

  const lastTaskMatch = content.match(/^Last task:\s*(\d+)\s+—/m);
  if (lastTaskMatch) {
    out.lastTaskId = parseInt(lastTaskMatch[1], 10);
  }

  // Next task id appears as "  id:    N" inside the Next task block.
  const nextTaskMatch = content.match(/^Next task:[\s\S]*?id:\s*(\d+)/m);
  if (nextTaskMatch) {
    out.nextTaskId = parseInt(nextTaskMatch[1], 10);
  }

  return out;
}

/**
 * One drift entry produced by checkHandoffDrift().
 *
 * - `field`: which handoff field disagrees with progress.json
 * - `expected`: the value computed from progress.json (canonical)
 * - `actual`: the value parsed from handoff.md (stale)
 */
export type HandoffDrift = {
  field: "feature" | "status" | "tasks" | "deferred" | "last_task" | "next_task";
  expected: string;
  actual: string;
};

/**
 * Compare a parsed handoff against a fresh ForgeProgress and return any
 * fields that disagree. Empty array = handoff matches progress.json.
 *
 * Caller is responsible for skipping this check when handoff.md is missing —
 * the absence is not drift, just an unrendered seed.
 */
export function checkHandoffDrift(
  progress: ForgeProgress,
  parsed: ParsedHandoff,
): HandoffDrift[] {
  const drifts: HandoffDrift[] = [];
  const expected = extractFields(progress, "");

  // Map ParsedHandoff fields to canonical strings derived from progress.
  const expectedFeature = expected.feature === "—" ? null : expected.feature;
  if (expectedFeature !== parsed.feature) {
    drifts.push({
      field: "feature",
      expected: String(expectedFeature),
      actual: String(parsed.feature),
    });
  }

  if (parsed.status !== null && parsed.status !== expected.status) {
    drifts.push({
      field: "status",
      expected: expected.status,
      actual: parsed.status,
    });
  }

  if (parsed.tasksRatio !== null && parsed.tasksRatio !== expected.tasksRatio) {
    drifts.push({
      field: "tasks",
      expected: expected.tasksRatio,
      actual: parsed.tasksRatio,
    });
  }

  if (
    parsed.deferredCount !== null &&
    parsed.deferredCount !== expected.deferredCount
  ) {
    drifts.push({
      field: "deferred",
      expected: String(expected.deferredCount),
      actual: String(parsed.deferredCount),
    });
  }

  const expectedLastId = expected.lastTask?.id ?? null;
  if (parsed.lastTaskId !== expectedLastId) {
    drifts.push({
      field: "last_task",
      expected: String(expectedLastId),
      actual: String(parsed.lastTaskId),
    });
  }

  const expectedNextId = expected.nextTask?.id ?? null;
  if (parsed.nextTaskId !== expectedNextId) {
    drifts.push({
      field: "next_task",
      expected: String(expectedNextId),
      actual: String(parsed.nextTaskId),
    });
  }

  return drifts;
}
