import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync } from "node:fs";
import { join } from "node:path";
import type { Command } from "commander";
import {
  detectMemoryFile,
  detectMonorepoProfiles,
  detectOptionalTool,
  detectProjectType,
  detectTestProfiles,
} from "../lib/detect.js";
import { gitNexusBaseline, isGitNexusInstalled } from "../lib/gitnexus.js";
import { FORGE_CLI_VERSION } from "../lib/version.js";
import { defaultConfig, writeConfig } from "../state/config.js";
import { idleProgress, progressPath, writeProgress } from "../state/progress.js";

/**
 * Claude Code hook commands for context management seed injection.
 * PreCompact: injects handoff state before compaction so /resume can recover.
 * PostCompact: re-injects after compaction in case the seed was partially lost.
 */
const CLAUDE_HOOKS_TEMPLATE = {
  PreCompact: [
    {
      matcher: "",
      hooks: [
        {
          type: "command",
          command: ".forge/bin/forge handoff:get",
        },
      ],
    },
  ],
  PostCompact: [
    {
      matcher: "",
      hooks: [
        {
          type: "command",
          command: ".forge/bin/forge handoff:get",
        },
      ],
    },
  ],
};

function writeJson(payload: unknown): void {
  process.stdout.write(`${JSON.stringify(payload)}\n`);
}

function ensureDirectory(path: string, created: string[]): void {
  if (!existsSync(path)) {
    created.push(path);
  }

  mkdirSync(path, { recursive: true });
}

function existingConfigError(cwd: string): string | null {
  const targetPath = join(cwd, ".forge", "config.json");

  if (!existsSync(targetPath)) {
    return null;
  }

  try {
    const config = JSON.parse(readFileSync(targetPath, "utf8")) as {
      version?: unknown;
    };

    if (config.version === "1.0") {
      return "config.json already exists; run migrate";
    }
  } catch {
    return "config.json already exists; run status or migrate";
  }

  return "config.json already exists; run status or migrate";
}

const GITNEXUS_IGNORE = `# Auto-generated by forge init.
# Patterns listed here are excluded from GitNexus indexing.

# Dependencies
node_modules/
vendor/
.venv/
__pycache__/
target/

# Build output
dist/
build/
out/
.next/
.nuxt/

# Test & coverage
coverage/
.nyc_output/
*.lcov

# Forge state (indexed separately)
.forge/

# IDE & OS
.idea/
.vscode/
*.swp
.DS_Store
Thumbs.db

# Logs & temp
*.log
tmp/
.tmp/

# Assets (not useful for code indexing)
*.png
*.jpg
*.jpeg
*.gif
*.svg
*.ico
*.woff
*.woff2
*.ttf
*.eot
*.mp4
*.webm
*.zip
*.tar.gz
*.pdf

# Lock files (large, low signal)
package-lock.json
pnpm-lock.yaml
yarn.lock
bun.lock
bun.lockb
Cargo.lock
poetry.lock
composer.lock
Gemfile.lock
go.sum
`;

/**
 * Write .gitnexusignore if it doesn't exist. This prevents GitNexus from
 * indexing dependencies, build output, binary assets, and other noise that
 * bloats the knowledge graph without adding useful code relationships.
 */
function ensureGitNexusIgnore(cwd: string): void {
  const ignorePath = join(cwd, ".gitnexusignore");
  if (existsSync(ignorePath)) return;
  writeFileSync(ignorePath, GITNEXUS_IGNORE, "utf8");
}

/**
 * If the project has a `.claude/` directory (indicating Claude Code usage),
 * ensure `.claude/settings.json` contains PreCompact and PostCompact hooks
 * for context management seed injection. Merges with existing settings
 * rather than overwriting.
 *
 * Returns true if hooks were written/updated.
 */
function ensureClaudeCodeHooks(cwd: string): boolean {
  const claudeDir = join(cwd, ".claude");
  if (!existsSync(claudeDir)) return false;

  const settingsPath = join(claudeDir, "settings.json");
  let settings: Record<string, any> = {};

  if (existsSync(settingsPath)) {
    try {
      settings = JSON.parse(readFileSync(settingsPath, "utf8"));
    } catch {
      // If settings.json is malformed, preserve it and don't modify
      return false;
    }
  }

  // Merge: only add hooks that don't already exist
  if (!settings.hooks) settings.hooks = {};
  let modified = false;

  for (const [event, hookDef] of Object.entries(CLAUDE_HOOKS_TEMPLATE)) {
    if (!settings.hooks[event]) {
      settings.hooks[event] = hookDef;
      modified = true;
    }
  }

  if (modified) {
    writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + "\n", "utf8");
  }
  return modified;
}

function ensureForgeSection(
  cwd: string,
  memoryFile: string,
  created: string[],
): void {
  const targetPath = join(cwd, memoryFile);
  const section = "## Forge\n\nForge project instructions live in `.forge/`.\n";

  if (!existsSync(targetPath)) {
    writeFileSync(targetPath, `# Project Instructions\n\n${section}`, "utf8");
    created.push(targetPath);
    return;
  }

  const existing = readFileSync(targetPath, "utf8");
  if (!/^## Forge$/m.test(existing)) {
    const separator = existing.endsWith("\n") ? "\n" : "\n\n";
    writeFileSync(targetPath, `${existing}${separator}${section}`, "utf8");
  }
}

/**
 * Generate cross-platform wrapper scripts in .forge/bin/.
 *
 * Skills can call `.forge/bin/forge <subcommand>` portably:
 * - bash / zsh / Git Bash → forge (POSIX shell script)
 * - cmd.exe / PowerShell  → forge.cmd (batch file)
 *
 * Both wrappers locate the forge CLI in this priority order:
 *   1. global `forge` on PATH
 *   2. ~/.config/opencode/plugins/forge/cli/dist/index.js (OpenCode install)
 *   3. node_modules/@forge/cli/dist/index.js (npm-local install)
 *
 * This removes the need for skills to embed FORGE_CMD resolution shell logic.
 */
function writeWrapperScripts(binDir: string, created: string[]): void {
  const posixWrapper = `#!/usr/bin/env sh
# Auto-generated by forge init. Locates the forge CLI and forwards args.
set -e

if command -v forge >/dev/null 2>&1; then
  exec forge "$@"
fi

OPENCODE_PATH="$HOME/.config/opencode/plugins/forge/cli/dist/index.js"
if [ -f "$OPENCODE_PATH" ]; then
  exec node "$OPENCODE_PATH" "$@"
fi

LOCAL_PATH="$(pwd)/node_modules/@forge/cli/dist/index.js"
if [ -f "$LOCAL_PATH" ]; then
  exec node "$LOCAL_PATH" "$@"
fi

echo "forge CLI not found — install with: npm install -g @forge/cli" >&2
exit 1
`;

  const cmdWrapper = `@echo off
REM Auto-generated by forge init. Locates the forge CLI and forwards args.
where forge >nul 2>nul
if %ERRORLEVEL% EQU 0 (
  forge %*
  exit /b %ERRORLEVEL%
)

set "OPENCODE_PATH=%USERPROFILE%\\.config\\opencode\\plugins\\forge\\cli\\dist\\index.js"
if exist "%OPENCODE_PATH%" (
  node "%OPENCODE_PATH%" %*
  exit /b %ERRORLEVEL%
)

set "LOCAL_PATH=%CD%\\node_modules\\@forge\\cli\\dist\\index.js"
if exist "%LOCAL_PATH%" (
  node "%LOCAL_PATH%" %*
  exit /b %ERRORLEVEL%
)

echo forge CLI not found ^- install with: npm install -g @forge/cli >&2
exit /b 1
`;

  const posixPath = join(binDir, "forge");
  const cmdPath = join(binDir, "forge.cmd");

  if (!existsSync(posixPath)) {
    writeFileSync(posixPath, posixWrapper, "utf8");
    try { chmodSync(posixPath, 0o755); } catch { /* Windows: ignore */ }
    created.push(posixPath);
  }
  if (!existsSync(cmdPath)) {
    writeFileSync(cmdPath, cmdWrapper, "utf8");
    created.push(cmdPath);
  }
}

export function registerInitCommand(program: Command): void {
  program
    .command("init")
    .option("--auto-detect", "detect project defaults")
    .option("--monorepo", "detect monorepo workspace profiles")
    .option(
      "--superpowers-available <value>",
      "whether superpowers are available",
    )
    .action((options: { autoDetect?: boolean; monorepo?: boolean; superpowersAvailable?: string }) => {
      const cwd = process.cwd();
      const created: string[] = [];
      const forgeDir = join(cwd, ".forge");
      const error = existingConfigError(cwd);

      if (error) {
        process.exitCode = 1;
        writeJson({
          ok: false,
          error,
        });
        return;
      }

      ensureDirectory(forgeDir, created);
      ensureDirectory(join(forgeDir, "specs"), created);
      ensureDirectory(join(forgeDir, "bin"), created);
      ensureDirectory(join(forgeDir, "backups"), created);

      writeWrapperScripts(join(forgeDir, "bin"), created);

      const monorepoResult = options.monorepo
        ? detectMonorepoProfiles(cwd)
        : null;

      let testProfiles = detectTestProfiles(cwd);
      if (monorepoResult?.monorepo && monorepoResult.detected_profiles.length > 0) {
        testProfiles = Object.fromEntries(
          monorepoResult.detected_profiles.map((p) => [
            p.name,
            {
              framework: p.framework,
              command: p.command,
              working_dir: p.working_dir,
              ...(p.coverage_command ? { coverage_command: p.coverage_command } : {}),
            },
          ]),
        );
      }

      const detected = {
        project_type: detectProjectType(cwd),
        memory_file: detectMemoryFile(cwd),
        test_profiles: testProfiles,
        gstack_installed: detectOptionalTool("gstack"),
      };

      const config = defaultConfig({
        memory_file: detected.memory_file,
        project_type: detected.project_type,
        test_profiles: detected.test_profiles,
        gstack_installed: detected.gstack_installed,
      });

      writeConfig(cwd, config);

      if (!existsSync(progressPath(cwd))) {
        writeProgress(cwd, idleProgress());
        created.push(progressPath(cwd));
      }

      ensureForgeSection(cwd, detected.memory_file, created);

      // GitNexus baseline index: non-blocking. Failure is a warning, not a
      // hard error, because init must succeed for the project to be usable.
      let gitnexus_baseline: { ok: boolean; error?: string } = { ok: false, error: "not installed" };
      if (isGitNexusInstalled()) {
        ensureGitNexusIgnore(cwd);
        const baselineResult = gitNexusBaseline(cwd);
        gitnexus_baseline = baselineResult.ok
          ? { ok: true }
          : { ok: false, error: baselineResult.stderr.slice(0, 300) };
      }

      // Claude Code hooks: inject PreCompact/PostCompact for context seed.
      const claude_hooks_written = ensureClaudeCodeHooks(cwd);

      writeJson({
        ok: true,
        detected,
        created,
        forge_cli_version: FORGE_CLI_VERSION,
        gitnexus_baseline,
        ...(monorepoResult?.monorepo ? { monorepo: true } : {}),
        ...(claude_hooks_written ? { claude_hooks_written: true } : {}),
      });
    });
}
