import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync, copyFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { Command } from "commander";
import {
  detectEnvironment,
  snapshotToConfig,
} from "../lib/environment-snapshot.js";
import { toEnvironmentReport } from "../lib/environment-report.js";
import { gitNexusBaseline, isGitNexusInstalled } from "../lib/gitnexus.js";
import { detectTerminalCapability } from "../lib/platform-detect.js";
import { FORGE_CLI_VERSION } from "../lib/version.js";
import { writeConfig } from "../state/config.js";
import { idleProgress, progressPath, writeProgress } from "../state/progress.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Path to the plugin's `hooks/` directory.
 *
 * In a normal install the CLI lives at `<plugin_root>/cli/dist/commands/`.
 * Walking up three levels lands on `<plugin_root>/`. We resolve the hooks
 * dir from there. CLAUDE_PLUGIN_ROOT, when set, takes precedence: Claude
 * Code exposes the canonical plugin root via that env var.
 */
function pluginHooksDir(): string {
  if (process.env.CLAUDE_PLUGIN_ROOT) {
    return join(process.env.CLAUDE_PLUGIN_ROOT, "hooks");
  }
  return resolve(__dirname, "../../../hooks");
}

/**
 * Claude Code hook commands for context management seed injection.
 * PreCompact: injects handoff state before compaction so /resume can recover.
 * PostCompact: re-injects after compaction in case the seed was partially lost.
 */
const CLAUDE_HOOKS_TEMPLATE = {
  PreCompact: [
    {
      matcher: "",
      hooks: [
        {
          type: "command",
          command: ".forge/bin/forge handoff:get",
        },
      ],
    },
  ],
  PostCompact: [
    {
      matcher: "",
      hooks: [
        {
          type: "command",
          command: ".forge/bin/forge handoff:get",
        },
      ],
    },
  ],
};

function writeJson(payload: unknown): void {
  process.stdout.write(`${JSON.stringify(payload)}\n`);
}

function ensureDirectory(path: string, created: string[]): void {
  if (!existsSync(path)) {
    created.push(path);
  }

  mkdirSync(path, { recursive: true });
}

function existingConfigError(cwd: string): string | null {
  const targetPath = join(cwd, ".forge", "config.json");

  if (!existsSync(targetPath)) {
    return null;
  }

  try {
    const config = JSON.parse(readFileSync(targetPath, "utf8")) as {
      version?: unknown;
    };

    if (config.version === "1.0") {
      return "config.json already exists; run migrate";
    }
  } catch {
    return "config.json already exists; run status or migrate";
  }

  return "config.json already exists; run status or migrate";
}

const GITNEXUS_IGNORE = `# Auto-generated by forge init.
# Patterns listed here are excluded from GitNexus indexing.

# Dependencies
node_modules/
vendor/
.venv/
__pycache__/
target/

# Build output
dist/
build/
out/
.next/
.nuxt/

# Test & coverage
coverage/
.nyc_output/
*.lcov

# Forge state (indexed separately)
.forge/

# IDE & OS
.idea/
.vscode/
*.swp
.DS_Store
Thumbs.db

# Logs & temp
*.log
tmp/
.tmp/

# Assets (not useful for code indexing)
*.png
*.jpg
*.jpeg
*.gif
*.svg
*.ico
*.woff
*.woff2
*.ttf
*.eot
*.mp4
*.webm
*.zip
*.tar.gz
*.pdf

# Lock files (large, low signal)
package-lock.json
pnpm-lock.yaml
yarn.lock
bun.lock
bun.lockb
Cargo.lock
poetry.lock
composer.lock
Gemfile.lock
go.sum
`;

/**
 * Write .gitnexusignore if it doesn't exist. This prevents GitNexus from
 * indexing dependencies, build output, binary assets, and other noise that
 * bloats the knowledge graph without adding useful code relationships.
 */
function ensureGitNexusIgnore(cwd: string): void {
  const ignorePath = join(cwd, ".gitnexusignore");
  if (existsSync(ignorePath)) return;
  writeFileSync(ignorePath, GITNEXUS_IGNORE, "utf8");
}

/**
 * Copy a context-manager hook script from the plugin's hooks/ folder into
 * the project's .forge/hooks/ folder. Returns the project-relative path the
 * Stop hook should reference, or null when the source script is missing.
 *
 * The .forge/hooks/ location is what hook script comments instruct users
 * to wire into .claude/settings.json — copying makes those instructions
 * actually work without the user touching CLAUDE_PLUGIN_ROOT manually.
 */
function copyContextManagerHook(
  cwd: string,
  filename: string,
  created: string[],
): string | null {
  const sourcePath = join(pluginHooksDir(), filename);
  if (!existsSync(sourcePath)) return null;

  const targetDir = join(cwd, ".forge", "hooks");
  ensureDirectory(targetDir, created);
  const targetPath = join(targetDir, filename);

  // Always overwrite: the plugin source is the authoritative version.
  // Skipping when target exists would let stale scripts rot in projects.
  copyFileSync(sourcePath, targetPath);
  if (!filename.endsWith(".cmd")) {
    try { chmodSync(targetPath, 0o755); } catch { /* Windows: ignore */ }
  }

  // Stop hook in settings.json uses repo-relative path so it works regardless
  // of where the user launches Claude Code from.
  return process.platform === "win32"
    ? `.forge\\hooks\\${filename}`
    : `.forge/hooks/${filename}`;
}

/**
 * Choose the right context-manager hook script for this terminal, copy it
 * into .forge/hooks/, and return the path to register as a Stop hook.
 *
 * Selection priority mirrors detectTerminalCapability():
 *   tmux → context-manager-tmux.sh
 *   wezterm → context-manager-wezterm.sh
 *   wt → context-manager-wt.cmd
 *   bare → null (no auto-handoff possible; user falls back to /compact)
 */
function selectStopHookScript(
  cwd: string,
  created: string[],
): string | null {
  const terminal = detectTerminalCapability();
  let filename: string | null = null;
  if (terminal.kind === "tmux") filename = "context-manager-tmux.sh";
  else if (terminal.kind === "wezterm") filename = "context-manager-wezterm.sh";
  else if (terminal.kind === "wt") filename = "context-manager-wt.cmd";
  if (!filename) return null;
  return copyContextManagerHook(cwd, filename, created);
}

/**
 * If the project has a `.claude/` directory (indicating Claude Code usage),
 * ensure `.claude/settings.json` contains PreCompact, PostCompact, and Stop
 * hooks for context management. Merges with existing settings rather than
 * overwriting.
 *
 * Stop hook is the missing link that consumes `.forge/handoff-signal.json`
 * when the context-manager plugin signals a handoff. Without it, the signal
 * file is written but never acted on, breaking the entire auto-handoff
 * chain. Selection is terminal-aware (tmux / wezterm / wt).
 *
 * Returns true if hooks were written/updated.
 */
function ensureClaudeCodeHooks(cwd: string, created: string[]): boolean {
  const claudeDir = join(cwd, ".claude");
  if (!existsSync(claudeDir)) return false;

  const settingsPath = join(claudeDir, "settings.json");
  let settings: Record<string, any> = {};

  if (existsSync(settingsPath)) {
    try {
      settings = JSON.parse(readFileSync(settingsPath, "utf8"));
    } catch {
      // If settings.json is malformed, preserve it and don't modify
      return false;
    }
  }

  // Merge: only add hooks that don't already exist
  if (!settings.hooks) settings.hooks = {};
  let modified = false;

  for (const [event, hookDef] of Object.entries(CLAUDE_HOOKS_TEMPLATE)) {
    if (!settings.hooks[event]) {
      settings.hooks[event] = hookDef;
      modified = true;
    }
  }

  // Stop hook: terminal-aware. Only registered when the script for the
  // detected terminal is available; otherwise we leave settings untouched
  // (the user gets Chain B / suggest-compact behaviour, which still works).
  if (!settings.hooks.Stop) {
    const stopScript = selectStopHookScript(cwd, created);
    if (stopScript) {
      settings.hooks.Stop = [
        {
          matcher: "",
          hooks: [
            {
              type: "command",
              command: stopScript,
            },
          ],
        },
      ];
      modified = true;
    }
  }

  if (modified) {
    writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + "\n", "utf8");
  }
  return modified;
}

function ensureForgeSection(
  cwd: string,
  memoryFile: string,
  created: string[],
): void {
  const targetPath = join(cwd, memoryFile);
  const section = "## Forge\n\nForge project instructions live in `.forge/`.\n";

  if (!existsSync(targetPath)) {
    writeFileSync(targetPath, `# Project Instructions\n\n${section}`, "utf8");
    created.push(targetPath);
    return;
  }

  const existing = readFileSync(targetPath, "utf8");
  if (!/^## Forge$/m.test(existing)) {
    const separator = existing.endsWith("\n") ? "\n" : "\n\n";
    writeFileSync(targetPath, `${existing}${separator}${section}`, "utf8");
  }
}

/**
 * Generate cross-platform wrapper scripts in .forge/bin/.
 *
 * Skills can call `.forge/bin/forge <subcommand>` portably:
 * - bash / zsh / Git Bash → forge (POSIX shell script)
 * - cmd.exe / PowerShell  → forge.cmd (batch file)
 *
 * Both wrappers locate the forge CLI in this priority order:
 *   1. global `forge` on PATH
 *   2. ~/.config/opencode/plugins/forge/cli/dist/index.js (OpenCode install)
 *   3. node_modules/@forge/cli/dist/index.js (npm-local install)
 *
 * This removes the need for skills to embed FORGE_CMD resolution shell logic.
 */
function writeWrapperScripts(binDir: string, created: string[]): void {
  const posixWrapper = `#!/usr/bin/env sh
# Auto-generated by forge init. Locates the forge CLI and forwards args.
set -e

if command -v forge >/dev/null 2>&1; then
  exec forge "$@"
fi

OPENCODE_PATH="$HOME/.config/opencode/plugins/forge/cli/dist/index.js"
if [ -f "$OPENCODE_PATH" ]; then
  exec node "$OPENCODE_PATH" "$@"
fi

LOCAL_PATH="$(pwd)/node_modules/@forge/cli/dist/index.js"
if [ -f "$LOCAL_PATH" ]; then
  exec node "$LOCAL_PATH" "$@"
fi

echo "forge CLI not found — install with: npm install -g @forge/cli" >&2
exit 1
`;

  const cmdWrapper = `@echo off
REM Auto-generated by forge init. Locates the forge CLI and forwards args.
where forge >nul 2>nul
if %ERRORLEVEL% EQU 0 (
  forge %*
  exit /b %ERRORLEVEL%
)

set "OPENCODE_PATH=%USERPROFILE%\\.config\\opencode\\plugins\\forge\\cli\\dist\\index.js"
if exist "%OPENCODE_PATH%" (
  node "%OPENCODE_PATH%" %*
  exit /b %ERRORLEVEL%
)

set "LOCAL_PATH=%CD%\\node_modules\\@forge\\cli\\dist\\index.js"
if exist "%LOCAL_PATH%" (
  node "%LOCAL_PATH%" %*
  exit /b %ERRORLEVEL%
)

echo forge CLI not found ^- install with: npm install -g @forge/cli >&2
exit /b 1
`;

  const posixPath = join(binDir, "forge");
  const cmdPath = join(binDir, "forge.cmd");

  if (!existsSync(posixPath)) {
    writeFileSync(posixPath, posixWrapper, "utf8");
    try { chmodSync(posixPath, 0o755); } catch { /* Windows: ignore */ }
    created.push(posixPath);
  }
  if (!existsSync(cmdPath)) {
    writeFileSync(cmdPath, cmdWrapper, "utf8");
    created.push(cmdPath);
  }
}

export function registerInitCommand(program: Command): void {
  program
    .command("init")
    .option("--auto-detect", "detect project defaults")
    .option("--monorepo", "detect monorepo workspace profiles")
    .option(
      "--superpowers-available <value>",
      "whether superpowers are available",
    )
    .action((options: { autoDetect?: boolean; monorepo?: boolean; superpowersAvailable?: string }) => {
      const cwd = process.cwd();
      const created: string[] = [];
      const forgeDir = join(cwd, ".forge");
      const error = existingConfigError(cwd);

      if (error) {
        process.exitCode = 1;
        writeJson({
          ok: false,
          error,
        });
        return;
      }

      ensureDirectory(forgeDir, created);
      ensureDirectory(join(forgeDir, "specs"), created);
      ensureDirectory(join(forgeDir, "bin"), created);
      ensureDirectory(join(forgeDir, "backups"), created);

      writeWrapperScripts(join(forgeDir, "bin"), created);

      // Single acquisition: run every detector exactly once. Both the config
      // and the environment_report below are projections of this snapshot, so
      // detection never runs twice and the two outputs stay consistent.
      const snapshot = detectEnvironment(cwd, { monorepo: options.monorepo });

      // init output contract: `detected` mirrors the historical shape.
      const detected = {
        project_type: snapshot.project_type,
        memory_file: snapshot.memory_file,
        test_profiles: snapshot.test_profiles,
        // gstack_installed reflects ONLY whether the CLI is on PATH, since
        // that is the only mode forge's verify subprocess can drive.
        gstack_installed: snapshot.gstack === "cli",
        gstack_skill_available: snapshot.gstack === "skill",
        gstack_availability: snapshot.gstack,
      };

      // Config is a pure projection of the snapshot. context_management is
      // auto-enabled inside snapshotToConfig only on platforms whose context
      // occupancy can be read (opencode / claude-code); window size is never
      // configured (it is derived from the model id on every read — see
      // lib/context-window.ts).
      const config = snapshotToConfig(snapshot);

      writeConfig(cwd, config);

      if (!existsSync(progressPath(cwd))) {
        writeProgress(cwd, idleProgress());
        created.push(progressPath(cwd));
      }

      ensureForgeSection(cwd, snapshot.memory_file, created);

      // GitNexus baseline index: non-blocking. Failure is a warning, not a
      // hard error, because init must succeed for the project to be usable.
      let gitnexus_baseline: { ok: boolean; error?: string } = { ok: false, error: "not installed" };
      if (isGitNexusInstalled()) {
        ensureGitNexusIgnore(cwd);
        const baselineResult = gitNexusBaseline(cwd);
        gitnexus_baseline = baselineResult.ok
          ? { ok: true }
          : { ok: false, error: baselineResult.stderr.slice(0, 300) };
      }

      // Claude Code hooks: inject PreCompact/PostCompact for context seed,
      // plus a Stop hook (terminal-aware) that drives the auto-handoff chain.
      const claude_hooks_written = ensureClaudeCodeHooks(cwd, created);

      // environment_report is the display projection of the SAME snapshot —
      // no second detection pass.
      const environment_report = toEnvironmentReport(snapshot);

      writeJson({
        ok: true,
        detected,
        created,
        forge_cli_version: FORGE_CLI_VERSION,
        gitnexus_baseline,
        ...(snapshot.monorepo?.monorepo ? { monorepo: true } : {}),
        ...(claude_hooks_written ? { claude_hooks_written: true } : {}),
        environment_report,
      });
    });
}
