@echo off
REM Install Forge plugin for OpenCode (Windows)
REM
REM 1. Clones the forge repo into %USERPROFILE%\.config\opencode\plugins\forge\
REM 2. Drops a forge.mjs bridge file into %USERPROFILE%\.config\opencode\plugins\
REM    so OpenCode's plugin loader picks it up (only root-level .js/.mjs/.ts
REM    files in plugins/ are auto-loaded; subdirectories are ignored).
REM 3. Creates a directory junction for every forge skill under
REM    %USERPROFILE%\.config\opencode\skills\<name> so OpenCode's documented
REM    skill discovery finds them and `/skills` lists them.

setlocal enabledelayedexpansion

set "OC_DIR=%USERPROFILE%\.config\opencode"
set "PLUGINS_DIR=%OC_DIR%\plugins"
set "SKILLS_DIR=%OC_DIR%\skills"
set "FORGE_DIR=%PLUGINS_DIR%\forge"
set "BRIDGE=%PLUGINS_DIR%\forge.mjs"
set "REPO_URL=https://github.com/waldenlake/forge.git"

if not exist "%PLUGINS_DIR%" mkdir "%PLUGINS_DIR%"
if not exist "%SKILLS_DIR%" mkdir "%SKILLS_DIR%"

REM --- 1. Clone or update repo ----------------------------------------------
if exist "%FORGE_DIR%\.git" (
  echo Updating forge in %FORGE_DIR%
  pushd "%FORGE_DIR%" >nul
  git pull --ff-only
  popd >nul
) else (
  if exist "%FORGE_DIR%" (
    echo %FORGE_DIR% exists but is not a git checkout, removing
    rmdir /s /q "%FORGE_DIR%"
  )
  echo Cloning forge into %FORGE_DIR%
  git clone "%REPO_URL%" "%FORGE_DIR%"
  if errorlevel 1 (
    echo Clone failed
    exit /b 1
  )
)

REM --- 2. Write bridge plugin -----------------------------------------------
echo Writing bridge plugin to %BRIDGE%
> "%BRIDGE%" echo // Auto-generated by forge install script. Re-exports the real forge plugin.
>> "%BRIDGE%" echo export { ForgePlugin } from './forge/.opencode/plugins/forge.js';

REM --- 3. Link skills into OpenCode's discovery path ------------------------
echo Linking skills into %SKILLS_DIR%
for %%S in (using-forge start next resume done bugfix scenarios progress-tracking session-handoff) do (
  set "SRC=%FORGE_DIR%\skills\%%S"
  set "DST=%SKILLS_DIR%\%%S"
  if exist "!DST!" (
    REM remove old link or directory before recreating
    rmdir "!DST!" 2>nul
    if exist "!DST!" rmdir /s /q "!DST!"
  )
  mklink /J "!DST!" "!SRC!" >nul
  if errorlevel 1 (
    echo   FAILED to link %%S, copying instead
    xcopy /e /i /q "!SRC!" "!DST!" >nul
  ) else (
    echo   linked %%S
  )
)

echo.
echo Done. Restart OpenCode and run `/skills` to verify.
endlocal
