@echo off
REM Install Forge plugin for OpenCode (Windows)
REM
REM 1. Clones the forge repo into %USERPROFILE%\.config\opencode\plugins\forge\
REM 2. Drops a forge.js bridge file into %USERPROFILE%\.config\opencode\plugins\
REM    (OpenCode only auto-loads .js files at the root of plugins/, not subdirs)

setlocal enabledelayedexpansion

set "OC_DIR=%USERPROFILE%\.config\opencode"
set "PLUGINS_DIR=%OC_DIR%\plugins"
set "FORGE_DIR=%PLUGINS_DIR%\forge"
set "BRIDGE=%PLUGINS_DIR%\forge.mjs"
set "REPO_URL=https://github.com/waldenlake/forge.git"

if not exist "%PLUGINS_DIR%" mkdir "%PLUGINS_DIR%"

if exist "%FORGE_DIR%\.git" (
  echo Updating forge in %FORGE_DIR%
  pushd "%FORGE_DIR%" >nul
  git pull --ff-only
  popd >nul
) else (
  if exist "%FORGE_DIR%" (
    echo %FORGE_DIR% exists but is not a git checkout, removing
    rmdir /s /q "%FORGE_DIR%"
  )
  echo Cloning forge into %FORGE_DIR%
  git clone "%REPO_URL%" "%FORGE_DIR%"
  if errorlevel 1 (
    echo Clone failed
    exit /b 1
  )
)

echo Writing bridge plugin to %BRIDGE%
> "%BRIDGE%" echo // Auto-generated by forge install script. Re-exports the real forge plugin.
>> "%BRIDGE%" echo export { ForgePlugin } from './forge/.opencode/plugins/forge.js';

echo.
echo Done. Restart OpenCode and run: use skill tool to list skills
endlocal
