#!/usr/bin/env bash
# Install Forge plugin for OpenCode (Linux / macOS)
#
# 1. Clones the forge repo into ~/.config/opencode/plugins/forge/
# 2. Drops a forge.js bridge file into ~/.config/opencode/plugins/
#    (OpenCode only auto-loads .js files at the root of plugins/, not subdirs)
set -euo pipefail

OC_DIR="${HOME}/.config/opencode"
PLUGINS_DIR="${OC_DIR}/plugins"
FORGE_DIR="${PLUGINS_DIR}/forge"
BRIDGE="${PLUGINS_DIR}/forge.mjs"
REPO_URL="https://github.com/waldenlake/forge.git"

mkdir -p "${PLUGINS_DIR}"

if [ -d "${FORGE_DIR}/.git" ]; then
  echo "Updating forge in ${FORGE_DIR}"
  git -C "${FORGE_DIR}" pull --ff-only
else
  if [ -e "${FORGE_DIR}" ]; then
    echo "${FORGE_DIR} exists but is not a git checkout, removing"
    rm -rf "${FORGE_DIR}"
  fi
  echo "Cloning forge into ${FORGE_DIR}"
  git clone "${REPO_URL}" "${FORGE_DIR}"
fi

echo "Writing bridge plugin to ${BRIDGE}"
cat > "${BRIDGE}" <<'JS'
// Auto-generated by forge install script. Re-exports the real forge plugin.
export { ForgePlugin } from './forge/.opencode/plugins/forge.js';
JS

echo
echo "Done. Restart OpenCode and run: use skill tool to list skills"
