#!/usr/bin/env bash
# Install Forge plugin for OpenCode (Linux / macOS)
#
# 1. Clones the forge repo into ~/.config/opencode/plugins/forge/
# 2. Drops forge.mjs and forge-tui.mjs bridge files into ~/.config/opencode/plugins/
#    so OpenCode's plugin loader picks it up (only root-level .js/.mjs/.ts
#    files in plugins/ are auto-loaded; subdirectories are ignored).
# 3. Merges ~/.config/opencode/tui.json so the TUI plugin loads.
# 4. Creates a symlink for every forge skill under
#    ~/.config/opencode/skills/<name> so OpenCode's documented skill
#    discovery finds them and `/skills` lists them.
set -euo pipefail

OC_DIR="${HOME}/.config/opencode"
PLUGINS_DIR="${OC_DIR}/plugins"
SKILLS_DIR="${OC_DIR}/skills"
FORGE_DIR="${PLUGINS_DIR}/forge"
BRIDGE="${PLUGINS_DIR}/forge.mjs"
TUI_BRIDGE="${PLUGINS_DIR}/forge-tui.mjs"
TUI_CONFIG="${OC_DIR}/tui.json"
REPO_URL="https://github.com/waldenlake/forge.git"

mkdir -p "${PLUGINS_DIR}" "${SKILLS_DIR}"

# --- 1. Clone or update repo ------------------------------------------------
if [ -d "${FORGE_DIR}/.git" ]; then
  echo "Updating forge in ${FORGE_DIR}"
  git -C "${FORGE_DIR}" pull --ff-only
else
  if [ -e "${FORGE_DIR}" ]; then
    echo "${FORGE_DIR} exists but is not a git checkout, removing"
    rm -rf "${FORGE_DIR}"
  fi
  echo "Cloning forge into ${FORGE_DIR}"
  git clone "${REPO_URL}" "${FORGE_DIR}"
fi

# --- 2. Build CLI runtime ---------------------------------------------------
echo "Building forge CLI"
(cd "${FORGE_DIR}/cli" && npm install --production=false && npm run build)

# --- 3. Write bridge plugin -------------------------------------------------
echo "Writing bridge plugin to ${BRIDGE}"
cat > "${BRIDGE}" <<'JS'
// Auto-generated by forge install script. Re-exports the real forge plugin.
export { ForgePlugin } from './forge/.opencode/plugins/forge.js';
JS

echo "Writing TUI bridge plugin to ${TUI_BRIDGE}"
cat > "${TUI_BRIDGE}" <<'JS'
// Auto-generated by forge install script. Re-exports the real forge TUI plugin.
export { default } from './forge/.opencode/plugins/forge-tui.js';
JS

echo "Merging Forge TUI plugin into ${TUI_CONFIG}"
node - "${TUI_CONFIG}" <<'NODE'
const fs = require('fs');
const file = process.argv[2];
const plugin = './plugins/forge-tui.mjs';
let config = { $schema: 'https://opencode.ai/tui.json', plugin: [] };
if (fs.existsSync(file)) {
  config = JSON.parse(fs.readFileSync(file, 'utf8'));
  if (!config || typeof config !== 'object' || Array.isArray(config)) {
    throw new Error(`${file} must contain a JSON object`);
  }
  if (config.plugin === undefined) config.plugin = [];
  if (!Array.isArray(config.plugin)) {
    throw new Error(`${file}.plugin must be an array`);
  }
  if (!config.$schema) config.$schema = 'https://opencode.ai/tui.json';
}
if (!config.plugin.includes(plugin)) config.plugin.push(plugin);
fs.writeFileSync(file, `${JSON.stringify(config, null, 2)}\n`, 'utf8');
NODE

# --- 4. Link skills into OpenCode's discovery path --------------------------
echo "Linking skills into ${SKILLS_DIR}"
for skill_dir in "${FORGE_DIR}/skills"/*/; do
  skill="$(basename "${skill_dir%/}")"
  src="${skill_dir%/}"
  dst="${SKILLS_DIR}/${skill}"

  if [ ! -f "${src}/SKILL.md" ]; then
    echo "  skipping ${skill} (no SKILL.md)"
    continue
  fi

  if [ -L "${dst}" ] || [ -e "${dst}" ]; then
    rm -rf "${dst}"
  fi

  if ln -s "${src}" "${dst}" 2>/dev/null; then
    echo "  linked ${skill}"
  else
    echo "  symlink failed for ${skill}, copying instead"
    cp -r "${src}" "${dst}"
  fi
done

echo
echo "Done. Restart OpenCode and run \`/skills\` to verify."
