@echo off
REM Install Forge plugin for OpenCode (Windows)
REM
REM 1. Clones the forge repo into %USERPROFILE%\.config\opencode\plugins\forge\
REM 2. Drops forge.mjs and forge-tui.mjs bridge files into %USERPROFILE%\.config\opencode\plugins\
REM    so OpenCode's plugin loader picks it up (only root-level .js/.mjs/.ts
REM    files in plugins/ are auto-loaded; subdirectories are ignored).
REM 3. Merges %USERPROFILE%\.config\opencode\tui.json so the TUI plugin loads.
REM 4. Creates a directory junction for every forge skill under
REM    %USERPROFILE%\.config\opencode\skills\<name> so OpenCode's documented
REM    skill discovery finds them and `/skills` lists them.

setlocal enabledelayedexpansion

set "OC_DIR=%USERPROFILE%\.config\opencode"
set "PLUGINS_DIR=%OC_DIR%\plugins"
set "SKILLS_DIR=%OC_DIR%\skills"
set "FORGE_DIR=%PLUGINS_DIR%\forge"
set "BRIDGE=%PLUGINS_DIR%\forge.mjs"
set "TUI_BRIDGE=%PLUGINS_DIR%\forge-tui.mjs"
set "TUI_CONFIG=%OC_DIR%\tui.json"
set "REPO_URL=https://github.com/waldenlake/forge.git"

if not exist "%PLUGINS_DIR%" mkdir "%PLUGINS_DIR%"
if not exist "%SKILLS_DIR%" mkdir "%SKILLS_DIR%"

REM --- 1. Clone or update repo ----------------------------------------------
if exist "%FORGE_DIR%\.git" (
  echo Updating forge in %FORGE_DIR%
  pushd "%FORGE_DIR%" >nul
  git pull --ff-only
  if errorlevel 1 (
    popd >nul
    exit /b 1
  )
  popd >nul
) else (
  if exist "%FORGE_DIR%" (
    echo %FORGE_DIR% exists but is not a git checkout, removing
    rmdir /s /q "%FORGE_DIR%"
  )
  echo Cloning forge into %FORGE_DIR%
  git clone "%REPO_URL%" "%FORGE_DIR%"
  if errorlevel 1 (
    echo Clone failed
    exit /b 1
  )
)

REM --- 2. Build CLI runtime -------------------------------------------------
echo Building forge CLI
pushd "%FORGE_DIR%\cli" >nul
call npm install --production=false
if errorlevel 1 (
  popd >nul
  exit /b 1
)
call npm run build
if errorlevel 1 (
  popd >nul
  exit /b 1
)
popd >nul

REM --- 3. Write bridge plugin -----------------------------------------------
echo Writing bridge plugin to %BRIDGE%
> "%BRIDGE%" echo // Auto-generated by forge install script. Re-exports the real forge plugin.
>> "%BRIDGE%" echo export { ForgePlugin } from './forge/.opencode/plugins/forge.js';

echo Writing TUI bridge plugin to %TUI_BRIDGE%
> "%TUI_BRIDGE%" echo // Auto-generated by forge install script. Re-exports the real forge TUI plugin.
>> "%TUI_BRIDGE%" echo export { default } from './forge/.opencode/plugins/forge-tui.js';

echo Merging Forge TUI plugin into %TUI_CONFIG%
node -e "const fs=require('fs'); const file=process.argv[1]; const plugin='./plugins/forge-tui.mjs'; let config={ '$schema':'https://opencode.ai/tui.json', plugin:[] }; if (fs.existsSync(file)) { config=JSON.parse(fs.readFileSync(file,'utf8')); if (config === null || typeof config !== 'object' || Array.isArray(config)) throw new Error(file + ' must contain a JSON object'); if (config.plugin === undefined) config.plugin=[]; if (Array.isArray(config.plugin) === false) throw new Error(file + '.plugin must be an array'); if (config.$schema === undefined || config.$schema === '') config.$schema='https://opencode.ai/tui.json'; } if (config.plugin.includes(plugin) === false) config.plugin.push(plugin); fs.writeFileSync(file, JSON.stringify(config,null,2) + '\n', 'utf8');" "%TUI_CONFIG%"
if errorlevel 1 (
  exit /b 1
)

REM --- 4. Link skills into OpenCode's discovery path ------------------------
echo Linking skills into %SKILLS_DIR%
for /d %%S in ("%FORGE_DIR%\skills\*") do (
  set "SKILL_NAME=%%~nxS"
  set "SRC=%%~fS"
  set "DST=%SKILLS_DIR%\%%~nxS"
  if not exist "%%~fS\SKILL.md" (
    echo   skipping %%~nxS ^(no SKILL.md^)
  ) else (
    if exist "!DST!" (
      rmdir "!DST!" 2>nul
      if exist "!DST!" rmdir /s /q "!DST!"
    )
    mklink /J "!DST!" "!SRC!" >nul
    if errorlevel 1 (
      echo   FAILED to link %%~nxS, copying instead
      xcopy /e /i /q "!SRC!" "!DST!" >nul
    ) else (
      echo   linked %%~nxS
    )
  )
)

echo.
echo Done. Restart OpenCode and run `/skills` to verify.
endlocal
