#!/usr/bin/env bash
# Install Forge plugin for OpenCode (Linux / macOS)
#
# 1. Clones the forge repo into ~/.config/opencode/plugins/forge/
# 2. Drops a forge.mjs bridge file into ~/.config/opencode/plugins/
#    so OpenCode's plugin loader picks it up (only root-level .js/.mjs/.ts
#    files in plugins/ are auto-loaded; subdirectories are ignored).
# 3. Creates a symlink for every forge skill under
#    ~/.config/opencode/skills/<name> so OpenCode's documented skill
#    discovery finds them and `/skills` lists them.
set -euo pipefail

OC_DIR="${HOME}/.config/opencode"
PLUGINS_DIR="${OC_DIR}/plugins"
SKILLS_DIR="${OC_DIR}/skills"
FORGE_DIR="${PLUGINS_DIR}/forge"
BRIDGE="${PLUGINS_DIR}/forge.mjs"
REPO_URL="https://github.com/waldenlake/forge.git"

SKILLS=(
  using-forge
  start
  next
  resume
  done
  bugfix
  scenarios
  progress-tracking
  session-handoff
)

mkdir -p "${PLUGINS_DIR}" "${SKILLS_DIR}"

# --- 1. Clone or update repo ------------------------------------------------
if [ -d "${FORGE_DIR}/.git" ]; then
  echo "Updating forge in ${FORGE_DIR}"
  git -C "${FORGE_DIR}" pull --ff-only
else
  if [ -e "${FORGE_DIR}" ]; then
    echo "${FORGE_DIR} exists but is not a git checkout, removing"
    rm -rf "${FORGE_DIR}"
  fi
  echo "Cloning forge into ${FORGE_DIR}"
  git clone "${REPO_URL}" "${FORGE_DIR}"
fi

# --- 2. Build CLI runtime ---------------------------------------------------
echo "Building forge CLI"
(cd "${FORGE_DIR}/cli" && npm install --production=false && npm run build)

# --- 3. Write bridge plugin -------------------------------------------------
echo "Writing bridge plugin to ${BRIDGE}"
cat > "${BRIDGE}" <<'JS'
// Auto-generated by forge install script. Re-exports the real forge plugin.
export { ForgePlugin } from './forge/.opencode/plugins/forge.js';
JS

# --- 4. Link skills into OpenCode's discovery path --------------------------
echo "Linking skills into ${SKILLS_DIR}"
for skill in "${SKILLS[@]}"; do
  src="${FORGE_DIR}/skills/${skill}"
  dst="${SKILLS_DIR}/${skill}"

  if [ -L "${dst}" ] || [ -e "${dst}" ]; then
    rm -rf "${dst}"
  fi

  if ln -s "${src}" "${dst}" 2>/dev/null; then
    echo "  linked ${skill}"
  else
    echo "  symlink failed for ${skill}, copying instead"
    cp -r "${src}" "${dst}"
  fi
done

echo
echo "Done. Restart OpenCode and run \`/skills\` to verify."
